
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/Utility Functions.ipynb
from collections.abc import Iterable

def listify(o):
    if o is None: return []
    if isinstance(o, list): return o
    if isinstance(o, str): return [o]
    if isinstance(o, Iterable): return list(o)
    return [o]

def setify(o): return o if isinstance(o, set) else set(listify(o))

def compose(x, funcs, order_key='_order', **kwargs):
    key = lambda x: getattr(x, order_key, 0)
    for f in sorted(listify(funcs), key=key): x = f(x, **kwargs)
    return x